// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// sqlc の入力となる SQL 定義。ここから型安全な Go コードを生成する。
	// 生成物はコミットし、手で編集しない。クエリを変えたいときはこの SQL を編集して再生成する。
	// SKU で在庫項目を 1 件取得する。存在しなければ pgx.ErrNoRows が返る。
	GetStockItemBySKU(ctx context.Context, sku string) (GetStockItemBySKURow, error)
	// 在庫項目を新規挿入する（version は 1 から始まる）。
	InsertStockItem(ctx context.Context, arg InsertStockItemParams) error
	// 楽観的排他制御つきの更新。期待バージョンが一致する行だけを更新し、
	// 影響行数を返す。0 行なら版が食い違っている（＝衝突）ことを意味する。
	UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
