// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/example/go-ddd-template/contexts/ordering/internal/application (interfaces: StockReserver,OrderStore,MessagePublisher,EventDispatcher,Repos)
//
// Generated by this command:
//
//	mockgen -typed -destination mock_application.go -package mock github.com/example/go-ddd-template/contexts/ordering/internal/application StockReserver,OrderStore,MessagePublisher,EventDispatcher,Repos
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	application "github.com/example/go-ddd-template/contexts/ordering/internal/application"
	order "github.com/example/go-ddd-template/contexts/ordering/internal/domain/order"
	port "github.com/example/go-ddd-template/contexts/ordering/port"
	outbox "github.com/example/go-ddd-template/shared/outbox"
	gomock "go.uber.org/mock/gomock"
)

// MockStockReserver is a mock of StockReserver interface.
type MockStockReserver struct {
	ctrl     *gomock.Controller
	recorder *MockStockReserverMockRecorder
	isgomock struct{}
}

// MockStockReserverMockRecorder is the mock recorder for MockStockReserver.
type MockStockReserverMockRecorder struct {
	mock *MockStockReserver
}

// NewMockStockReserver creates a new mock instance.
func NewMockStockReserver(ctrl *gomock.Controller) *MockStockReserver {
	mock := &MockStockReserver{ctrl: ctrl}
	mock.recorder = &MockStockReserverMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockReserver) EXPECT() *MockStockReserverMockRecorder {
	return m.recorder
}

// Release mocks base method.
func (m *MockStockReserver) Release(ctx context.Context, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Release", ctx, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Release indicates an expected call of Release.
func (mr *MockStockReserverMockRecorder) Release(ctx, ref any) *MockStockReserverReleaseCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Release", reflect.TypeOf((*MockStockReserver)(nil).Release), ctx, ref)
	return &MockStockReserverReleaseCall{Call: call}
}

// MockStockReserverReleaseCall wrap *gomock.Call
type MockStockReserverReleaseCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockReserverReleaseCall) Return(arg0 error) *MockStockReserverReleaseCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockReserverReleaseCall) Do(f func(context.Context, string) error) *MockStockReserverReleaseCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockReserverReleaseCall) DoAndReturn(f func(context.Context, string) error) *MockStockReserverReleaseCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Reserve mocks base method.
func (m *MockStockReserver) Reserve(ctx context.Context, ref string, lines []port.ReserveLine) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reserve", ctx, ref, lines)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reserve indicates an expected call of Reserve.
func (mr *MockStockReserverMockRecorder) Reserve(ctx, ref, lines any) *MockStockReserverReserveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reserve", reflect.TypeOf((*MockStockReserver)(nil).Reserve), ctx, ref, lines)
	return &MockStockReserverReserveCall{Call: call}
}

// MockStockReserverReserveCall wrap *gomock.Call
type MockStockReserverReserveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockReserverReserveCall) Return(arg0 error) *MockStockReserverReserveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockReserverReserveCall) Do(f func(context.Context, string, []port.ReserveLine) error) *MockStockReserverReserveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockReserverReserveCall) DoAndReturn(f func(context.Context, string, []port.ReserveLine) error) *MockStockReserverReserveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockOrderStore is a mock of OrderStore interface.
type MockOrderStore struct {
	ctrl     *gomock.Controller
	recorder *MockOrderStoreMockRecorder
	isgomock struct{}
}

// MockOrderStoreMockRecorder is the mock recorder for MockOrderStore.
type MockOrderStoreMockRecorder struct {
	mock *MockOrderStore
}

// NewMockOrderStore creates a new mock instance.
func NewMockOrderStore(ctrl *gomock.Controller) *MockOrderStore {
	mock := &MockOrderStore{ctrl: ctrl}
	mock.recorder = &MockOrderStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOrderStore) EXPECT() *MockOrderStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockOrderStore) Load(ctx context.Context, id order.OrderID) (*order.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, id)
	ret0, _ := ret[0].(*order.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockOrderStoreMockRecorder) Load(ctx, id any) *MockOrderStoreLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockOrderStore)(nil).Load), ctx, id)
	return &MockOrderStoreLoadCall{Call: call}
}

// MockOrderStoreLoadCall wrap *gomock.Call
type MockOrderStoreLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderStoreLoadCall) Return(arg0 *order.Order, arg1 error) *MockOrderStoreLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderStoreLoadCall) Do(f func(context.Context, order.OrderID) (*order.Order, error)) *MockOrderStoreLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderStoreLoadCall) DoAndReturn(f func(context.Context, order.OrderID) (*order.Order, error)) *MockOrderStoreLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockOrderStore) Save(ctx context.Context, o *order.Order) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, o)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockOrderStoreMockRecorder) Save(ctx, o any) *MockOrderStoreSaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockOrderStore)(nil).Save), ctx, o)
	return &MockOrderStoreSaveCall{Call: call}
}

// MockOrderStoreSaveCall wrap *gomock.Call
type MockOrderStoreSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockOrderStoreSaveCall) Return(arg0 error) *MockOrderStoreSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockOrderStoreSaveCall) Do(f func(context.Context, *order.Order) error) *MockOrderStoreSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockOrderStoreSaveCall) DoAndReturn(f func(context.Context, *order.Order) error) *MockOrderStoreSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
	isgomock struct{}
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m_2 *MockMessagePublisher) Enqueue(ctx context.Context, m outbox.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Enqueue", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockMessagePublisherMockRecorder) Enqueue(ctx, m any) *MockMessagePublisherEnqueueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockMessagePublisher)(nil).Enqueue), ctx, m)
	return &MockMessagePublisherEnqueueCall{Call: call}
}

// MockMessagePublisherEnqueueCall wrap *gomock.Call
type MockMessagePublisherEnqueueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagePublisherEnqueueCall) Return(arg0 error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagePublisherEnqueueCall) Do(f func(context.Context, outbox.Message) error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagePublisherEnqueueCall) DoAndReturn(f func(context.Context, outbox.Message) error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEventDispatcher is a mock of EventDispatcher interface.
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatcherMockRecorder
	isgomock struct{}
}

// MockEventDispatcherMockRecorder is the mock recorder for MockEventDispatcher.
type MockEventDispatcherMockRecorder struct {
	mock *MockEventDispatcher
}

// NewMockEventDispatcher creates a new mock instance.
func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatcher) EXPECT() *MockEventDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockEventDispatcher) Dispatch(ctx context.Context, events ...order.DomainEvent) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Dispatch", varargs...)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockEventDispatcherMockRecorder) Dispatch(ctx any, events ...any) *MockEventDispatcherDispatchCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, events...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockEventDispatcher)(nil).Dispatch), varargs...)
	return &MockEventDispatcherDispatchCall{Call: call}
}

// MockEventDispatcherDispatchCall wrap *gomock.Call
type MockEventDispatcherDispatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventDispatcherDispatchCall) Return() *MockEventDispatcherDispatchCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventDispatcherDispatchCall) Do(f func(context.Context, ...order.DomainEvent)) *MockEventDispatcherDispatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventDispatcherDispatchCall) DoAndReturn(f func(context.Context, ...order.DomainEvent)) *MockEventDispatcherDispatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// Orders mocks base method.
func (m *MockRepos) Orders() application.OrderStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Orders")
	ret0, _ := ret[0].(application.OrderStore)
	return ret0
}

// Orders indicates an expected call of Orders.
func (mr *MockReposMockRecorder) Orders() *MockReposOrdersCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Orders", reflect.TypeOf((*MockRepos)(nil).Orders))
	return &MockReposOrdersCall{Call: call}
}

// MockReposOrdersCall wrap *gomock.Call
type MockReposOrdersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReposOrdersCall) Return(arg0 application.OrderStore) *MockReposOrdersCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReposOrdersCall) Do(f func() application.OrderStore) *MockReposOrdersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReposOrdersCall) DoAndReturn(f func() application.OrderStore) *MockReposOrdersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Outbox mocks base method.
func (m *MockRepos) Outbox() application.MessagePublisher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Outbox")
	ret0, _ := ret[0].(application.MessagePublisher)
	return ret0
}

// Outbox indicates an expected call of Outbox.
func (mr *MockReposMockRecorder) Outbox() *MockReposOutboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Outbox", reflect.TypeOf((*MockRepos)(nil).Outbox))
	return &MockReposOutboxCall{Call: call}
}

// MockReposOutboxCall wrap *gomock.Call
type MockReposOutboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReposOutboxCall) Return(arg0 application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReposOutboxCall) Do(f func() application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReposOutboxCall) DoAndReturn(f func() application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
