// Code generated by ogen, DO NOT EDIT.

package invclient

// ConfirmReservationParams is parameters of confirmReservation operation.
type ConfirmReservationParams struct {
	// 予約参照（不透明な相関 ID）.
	Ref string
}

// ReleaseReservationParams is parameters of releaseReservation operation.
type ReleaseReservationParams struct {
	// 予約参照（不透明な相関 ID）.
	Ref string
}
