// Code generated by ogen, DO NOT EDIT.

package invclient

import (
	"context"
	"io"
	"net/url"
	"strings"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	ht "github.com/ogen-go/ogen/http"
	"github.com/ogen-go/ogen/uri"
)

func trimTrailingSlashes(u *url.URL) {
	u.Path = strings.TrimRight(u.Path, "/")
	u.RawPath = strings.TrimRight(u.RawPath, "/")
}

// Invoker invokes operations described by OpenAPI v3 specification.
type Invoker interface {
	// ConfirmReservation invokes confirmReservation operation.
	//
	// 指定参照の予約を確定する。有効な予約が無ければ 404 を返す。.
	//
	// POST /reservations/{ref}/confirm
	ConfirmReservation(ctx context.Context, params ConfirmReservationParams) (*Ack, error)
	// IngestEvent invokes ingestEvent operation.
	//
	// 受信したメッセージを outbox.Router へ委譲し、message_type に応じた Consumer
	// が処理する。 未登録の種別は 422 を返す（黙って捨てない）。payload
	// は翻訳済み契約のシリアライズ（JSON 文字列）。.
	//
	// POST /events
	IngestEvent(ctx context.Context, request *InboundMessage) (*Ack, error)
	// ReleaseReservation invokes releaseReservation operation.
	//
	// 指定参照の予約を解放して在庫を戻す。未知・解放済みの参照でも冪等に成功する。.
	//
	// POST /reservations/{ref}/release
	ReleaseReservation(ctx context.Context, params ReleaseReservationParams) (*Ack, error)
	// ReserveStock invokes reserveStock operation.
	//
	// 1 つの予約参照に対して複数 SKU をまとめて仮予約する。1
	// つでも在庫不足なら全体を失敗させる。.
	//
	// POST /reservations
	ReserveStock(ctx context.Context, request *ReserveCommand) (*Ack, error)
}

// Client implements OAS client.
type Client struct {
	serverURL *url.URL
	baseClient
}

// NewClient initializes new Client defined by OAS.
func NewClient(serverURL string, opts ...ClientOption) (*Client, error) {
	u, err := url.Parse(serverURL)
	if err != nil {
		return nil, err
	}
	trimTrailingSlashes(u)

	c, err := newClientConfig(opts...).baseClient()
	if err != nil {
		return nil, err
	}
	return &Client{
		serverURL:  u,
		baseClient: c,
	}, nil
}

type serverURLKey struct{}

// WithServerURL sets context key to override server URL.
func WithServerURL(ctx context.Context, u *url.URL) context.Context {
	return context.WithValue(ctx, serverURLKey{}, u)
}

func (c *Client) requestURL(ctx context.Context) *url.URL {
	u, ok := ctx.Value(serverURLKey{}).(*url.URL)
	if !ok {
		return c.serverURL
	}
	return u
}

// ConfirmReservation invokes confirmReservation operation.
//
// 指定参照の予約を確定する。有効な予約が無ければ 404 を返す。.
//
// POST /reservations/{ref}/confirm
func (c *Client) ConfirmReservation(ctx context.Context, params ConfirmReservationParams) (*Ack, error) {
	res, err := c.sendConfirmReservation(ctx, params)
	return res, err
}

func (c *Client) sendConfirmReservation(ctx context.Context, params ConfirmReservationParams) (res *Ack, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/reservations/"
	{
		// Encode "ref" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "ref",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Ref))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/confirm"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeConfirmReservationResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// IngestEvent invokes ingestEvent operation.
//
// 受信したメッセージを outbox.Router へ委譲し、message_type に応じた Consumer
// が処理する。 未登録の種別は 422 を返す（黙って捨てない）。payload
// は翻訳済み契約のシリアライズ（JSON 文字列）。.
//
// POST /events
func (c *Client) IngestEvent(ctx context.Context, request *InboundMessage) (*Ack, error) {
	res, err := c.sendIngestEvent(ctx, request)
	return res, err
}

func (c *Client) sendIngestEvent(ctx context.Context, request *InboundMessage) (res *Ack, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/events"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeIngestEventRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeIngestEventResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReleaseReservation invokes releaseReservation operation.
//
// 指定参照の予約を解放して在庫を戻す。未知・解放済みの参照でも冪等に成功する。.
//
// POST /reservations/{ref}/release
func (c *Client) ReleaseReservation(ctx context.Context, params ReleaseReservationParams) (*Ack, error) {
	res, err := c.sendReleaseReservation(ctx, params)
	return res, err
}

func (c *Client) sendReleaseReservation(ctx context.Context, params ReleaseReservationParams) (res *Ack, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [3]string
	pathParts[0] = "/reservations/"
	{
		// Encode "ref" parameter.
		e := uri.NewPathEncoder(uri.PathEncoderConfig{
			Param:   "ref",
			Style:   uri.PathStyleSimple,
			Explode: false,
		})
		if err := func() error {
			return e.EncodeValue(conv.StringToString(params.Ref))
		}(); err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		encoded, err := e.Result()
		if err != nil {
			return res, errors.Wrap(err, "encode path")
		}
		pathParts[1] = encoded
	}
	pathParts[2] = "/release"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeReleaseReservationResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}

// ReserveStock invokes reserveStock operation.
//
// 1 つの予約参照に対して複数 SKU をまとめて仮予約する。1
// つでも在庫不足なら全体を失敗させる。.
//
// POST /reservations
func (c *Client) ReserveStock(ctx context.Context, request *ReserveCommand) (*Ack, error) {
	res, err := c.sendReserveStock(ctx, request)
	return res, err
}

func (c *Client) sendReserveStock(ctx context.Context, request *ReserveCommand) (res *Ack, err error) {

	u := uri.Clone(c.requestURL(ctx))
	var pathParts [1]string
	pathParts[0] = "/reservations"
	uri.AddPathParts(u, pathParts[:]...)

	r, err := ht.NewRequest(ctx, "POST", u)
	if err != nil {
		return res, errors.Wrap(err, "create request")
	}
	if err := encodeReserveStockRequest(request, r); err != nil {
		return res, errors.Wrap(err, "encode request")
	}

	resp, err := c.cfg.Client.Do(r)
	if err != nil {
		return res, errors.Wrap(err, "do request")
	}
	body := resp.Body
	defer func() {
		// Drain the body to EOF before closing, so the underlying
		// connection can be reused by the Transport regardless of the
		// response status code. See https://github.com/ogen-go/ogen/issues/1670.
		_, _ = io.Copy(io.Discard, body)
		_ = body.Close()
	}()

	result, err := decodeReserveStockResponse(resp)
	if err != nil {
		return res, errors.Wrap(err, "decode response")
	}

	return result, nil
}
