-- 注文コンテキストの「本番参照データ」（production reference data）。冪等な upsert。
--
-- 注文コンテキストのテーブル（orders / order_lines / shipments / outbox / events）は
-- いずれも実行時に作られるトランザクションデータであり、事前に投入すべき参照データ
-- （マスタ）は存在しない。
-- したがってこの seed は現時点で空である。
--
-- このファイルを空でも用意しておくのは、各コンテキストが「schema / roles / seed / fixtures」
-- の 4 点セットを対称に持つ構造を示し、参照データが生じたときの投入先を明確にするため。
-- 参照データを足す場合は、ここに ON CONFLICT DO NOTHING などの冪等 upsert を書く
-- （dev/test 専用のデモデータは fixtures.sql に分離する）。

-- （現時点では参照データなし）
