// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"net/url"
)

func (s *ProblemResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RFC 9457 (Problem Details for HTTP APIs) に準拠したエラー表現.
// Ref: #/components/schemas/ProblemDetails
type ProblemDetails struct {
	// 問題の種別を示す URI。既定は "about:blank"。.
	Type url.URL `json:"type"`
	// 問題種別の短い人間可読な要約.
	Title string `json:"title"`
	// HTTP ステータスコード.
	Status int `json:"status"`
	// 今回の発生に固有の人間可読な説明.
	Detail OptString `json:"detail"`
	// 問題が発生した具体的なリソースを示す URI.
	Instance OptURI `json:"instance"`
}

// GetType returns the value of Type.
func (s *ProblemDetails) GetType() url.URL {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ProblemDetails) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *ProblemDetails) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *ProblemDetails) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *ProblemDetails) GetInstance() OptURI {
	return s.Instance
}

// SetType sets the value of Type.
func (s *ProblemDetails) SetType(val url.URL) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ProblemDetails) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *ProblemDetails) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *ProblemDetails) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *ProblemDetails) SetInstance(val OptURI) {
	s.Instance = val
}

// ProblemResponseStatusCode wraps ProblemDetails with StatusCode.
type ProblemResponseStatusCode struct {
	StatusCode int
	Response   ProblemDetails
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemResponseStatusCode) GetResponse() ProblemDetails {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemResponseStatusCode) SetResponse(val ProblemDetails) {
	s.Response = val
}

// Ref: #/components/schemas/ReplenishRequest
type ReplenishRequest struct {
	// 補充する数量。値の妥当性検証はドメイン層が行う。.
	Quantity int `json:"quantity"`
}

// GetQuantity returns the value of Quantity.
func (s *ReplenishRequest) GetQuantity() int {
	return s.Quantity
}

// SetQuantity sets the value of Quantity.
func (s *ReplenishRequest) SetQuantity(val int) {
	s.Quantity = val
}

// Ref: #/components/schemas/StockView
type StockView struct {
	// 在庫識別子.
	Sku string `json:"sku"`
	// 利用可能在庫数.
	Available int `json:"available"`
	// 引当済み在庫数（本スライスでは常に 0）.
	Reserved int `json:"reserved"`
	// 楽観的排他制御のためのバージョン番号.
	Version int `json:"version"`
}

// GetSku returns the value of Sku.
func (s *StockView) GetSku() string {
	return s.Sku
}

// GetAvailable returns the value of Available.
func (s *StockView) GetAvailable() int {
	return s.Available
}

// GetReserved returns the value of Reserved.
func (s *StockView) GetReserved() int {
	return s.Reserved
}

// GetVersion returns the value of Version.
func (s *StockView) GetVersion() int {
	return s.Version
}

// SetSku sets the value of Sku.
func (s *StockView) SetSku(val string) {
	s.Sku = val
}

// SetAvailable sets the value of Available.
func (s *StockView) SetAvailable(val int) {
	s.Available = val
}

// SetReserved sets the value of Reserved.
func (s *StockView) SetReserved(val int) {
	s.Reserved = val
}

// SetVersion sets the value of Version.
func (s *StockView) SetVersion(val int) {
	s.Version = val
}
