// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type InventoryEvent struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
	RecordedAt  pgtype.Timestamptz
}

type InventoryOutbox struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}

type InventoryStockItem struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type InventoryStockReservation struct {
	StockItemID string
	Ref         string
	Quantity    int32
	Status      string
	ExpiresAt   pgtype.Timestamptz
}
