// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const getStockItemBySKU = `-- name: GetStockItemBySKU :one

SELECT id, sku, available, version
FROM inventory.stock_items
WHERE sku = $1
`

type GetStockItemBySKURow struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
}

// sqlc の入力となる SQL 定義。ここから型安全な Go コードを生成する。
// 生成物はコミットし、手で編集しない。クエリを変えたいときはこの SQL を編集して再生成する。
// SKU で在庫項目を 1 件取得する。存在しなければ pgx.ErrNoRows が返る。
func (q *Queries) GetStockItemBySKU(ctx context.Context, sku string) (GetStockItemBySKURow, error) {
	row := q.db.QueryRow(ctx, getStockItemBySKU, sku)
	var i GetStockItemBySKURow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Available,
		&i.Version,
	)
	return i, err
}

const insertStockItem = `-- name: InsertStockItem :exec
INSERT INTO inventory.stock_items (id, sku, available, version)
VALUES ($1, $2, $3, $4)
`

type InsertStockItemParams struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
}

// 在庫項目を新規挿入する（version は 1 から始まる）。
func (q *Queries) InsertStockItem(ctx context.Context, arg InsertStockItemParams) error {
	_, err := q.db.Exec(ctx, insertStockItem,
		arg.ID,
		arg.Sku,
		arg.Available,
		arg.Version,
	)
	return err
}

const updateStockItem = `-- name: UpdateStockItem :execrows
UPDATE inventory.stock_items
SET available = $1, version = $2, updated_at = now()
WHERE sku = $3 AND version = $4
`

type UpdateStockItemParams struct {
	Available int32
	Version   int32
	Sku       string
	Version_2 int32
}

// 楽観的排他制御つきの更新。期待バージョンが一致する行だけを更新し、
// 影響行数を返す。0 行なら版が食い違っている（＝衝突）ことを意味する。
func (q *Queries) UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStockItem,
		arg.Available,
		arg.Version,
		arg.Sku,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
