// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteReservationsByStockItem = `-- name: DeleteReservationsByStockItem :exec
DELETE FROM inventory.stock_reservations
WHERE stock_item_id = $1
`

// 在庫項目の予約を全削除する（集約の予約状態を「削除して入れ直す」スナップショット保存の前段）。
func (q *Queries) DeleteReservationsByStockItem(ctx context.Context, stockItemID string) error {
	_, err := q.db.Exec(ctx, deleteReservationsByStockItem, stockItemID)
	return err
}

const getStockItemByID = `-- name: GetStockItemByID :one
SELECT id, sku, available, version
FROM inventory.stock_items
WHERE id = $1
`

type GetStockItemByIDRow struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
}

// ID で在庫項目を 1 件取得する（予約参照や期限切れ検索で得た ID から復元する用）。
func (q *Queries) GetStockItemByID(ctx context.Context, id string) (GetStockItemByIDRow, error) {
	row := q.db.QueryRow(ctx, getStockItemByID, id)
	var i GetStockItemByIDRow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Available,
		&i.Version,
	)
	return i, err
}

const getStockItemBySKU = `-- name: GetStockItemBySKU :one

SELECT id, sku, available, version
FROM inventory.stock_items
WHERE sku = $1
`

type GetStockItemBySKURow struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
}

// sqlc の入力となる SQL 定義。ここから型安全な Go コードを生成する。
// 生成物はコミットし、手で編集しない。クエリを変えたいときはこの SQL を編集して再生成する。
// SKU で在庫項目を 1 件取得する。存在しなければ pgx.ErrNoRows が返る。
func (q *Queries) GetStockItemBySKU(ctx context.Context, sku string) (GetStockItemBySKURow, error) {
	row := q.db.QueryRow(ctx, getStockItemBySKU, sku)
	var i GetStockItemBySKURow
	err := row.Scan(
		&i.ID,
		&i.Sku,
		&i.Available,
		&i.Version,
	)
	return i, err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO inventory.events (id, message_type, payload, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertEventParams struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}

// 恒久イベントログへ発行メッセージを 1 件記録する（recorded_at は既定値 now()）。
// InsertOutboxMessage と同一トランザクションで実行し、原子的に確定させる。
func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.Exec(ctx, insertEvent,
		arg.ID,
		arg.MessageType,
		arg.Payload,
		arg.TraceID,
		arg.OccurredAt,
	)
	return err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO inventory.outbox (id, message_type, payload, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxMessageParams struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}

// アウトボックス（一時的な配送キュー）へメッセージを積む。
// 集約書き込み・InsertEvent と同一トランザクションで実行する。
func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage,
		arg.ID,
		arg.MessageType,
		arg.Payload,
		arg.TraceID,
		arg.OccurredAt,
	)
	return err
}

const insertReservation = `-- name: InsertReservation :exec
INSERT INTO inventory.stock_reservations (stock_item_id, ref, quantity, status, expires_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertReservationParams struct {
	StockItemID string
	Ref         string
	Quantity    int32
	Status      string
	ExpiresAt   pgtype.Timestamptz
}

// 予約を 1 件挿入する。
func (q *Queries) InsertReservation(ctx context.Context, arg InsertReservationParams) error {
	_, err := q.db.Exec(ctx, insertReservation,
		arg.StockItemID,
		arg.Ref,
		arg.Quantity,
		arg.Status,
		arg.ExpiresAt,
	)
	return err
}

const insertStockItem = `-- name: InsertStockItem :exec
INSERT INTO inventory.stock_items (id, sku, available, version)
VALUES ($1, $2, $3, $4)
`

type InsertStockItemParams struct {
	ID        string
	Sku       string
	Available int32
	Version   int32
}

// 在庫項目を新規挿入する（version は 1 から始まる）。
func (q *Queries) InsertStockItem(ctx context.Context, arg InsertStockItemParams) error {
	_, err := q.db.Exec(ctx, insertStockItem,
		arg.ID,
		arg.Sku,
		arg.Available,
		arg.Version,
	)
	return err
}

const listExpiredPendingStockItemIDs = `-- name: ListExpiredPendingStockItemIDs :many
SELECT DISTINCT stock_item_id
FROM inventory.stock_reservations
WHERE status = 'pending' AND expires_at IS NOT NULL AND expires_at < $1
LIMIT $2
`

type ListExpiredPendingStockItemIDsParams struct {
	ExpiresAt pgtype.Timestamptz
	Limit     int32
}

// before 時点で期限切れの pending 予約を持つ在庫項目の ID 一覧を取得する（Reaper）。
func (q *Queries) ListExpiredPendingStockItemIDs(ctx context.Context, arg ListExpiredPendingStockItemIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingStockItemIDs, arg.ExpiresAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var stock_item_id string
		if err := rows.Scan(&stock_item_id); err != nil {
			return nil, err
		}
		items = append(items, stock_item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReservationsByStockItem = `-- name: ListReservationsByStockItem :many
SELECT stock_item_id, ref, quantity, status, expires_at
FROM inventory.stock_reservations
WHERE stock_item_id = $1
`

// 在庫項目が保持する予約の一覧を取得する。
func (q *Queries) ListReservationsByStockItem(ctx context.Context, stockItemID string) ([]InventoryStockReservation, error) {
	rows, err := q.db.Query(ctx, listReservationsByStockItem, stockItemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryStockReservation{}
	for rows.Next() {
		var i InventoryStockReservation
		if err := rows.Scan(
			&i.StockItemID,
			&i.Ref,
			&i.Quantity,
			&i.Status,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockItemIDsByReservationRef = `-- name: ListStockItemIDsByReservationRef :many
SELECT DISTINCT stock_item_id
FROM inventory.stock_reservations
WHERE ref = $1
`

// 指定の予約参照を持つ在庫項目の ID 一覧を取得する（Confirm / Release のマルチ SKU ロード）。
func (q *Queries) ListStockItemIDsByReservationRef(ctx context.Context, ref string) ([]string, error) {
	rows, err := q.db.Query(ctx, listStockItemIDsByReservationRef, ref)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var stock_item_id string
		if err := rows.Scan(&stock_item_id); err != nil {
			return nil, err
		}
		items = append(items, stock_item_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, message_type, payload, trace_id, occurred_at
FROM inventory.outbox
ORDER BY occurred_at ASC
LIMIT $1
`

// 未送信のメッセージを occurred_at 昇順で最大 $1 件取得する。
// 送信済みの行は削除されるため、この表に残っている行はすべて未送信である。
func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]InventoryOutbox, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InventoryOutbox{}
	for rows.Next() {
		var i InventoryOutbox
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.Payload,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
DELETE FROM inventory.outbox
WHERE id = $1
`

// 送信に成功した ID の行を配送キューから削除する（delete-after-publish）。
// 発行履歴は events テーブルに残るため、ここで削除しても記録は失われない。
func (q *Queries) MarkOutboxPublished(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const updateStockItem = `-- name: UpdateStockItem :execrows
UPDATE inventory.stock_items
SET available = $1, version = $2, updated_at = now()
WHERE sku = $3 AND version = $4
`

type UpdateStockItemParams struct {
	Available int32
	Version   int32
	Sku       string
	Version_2 int32
}

// 楽観的排他制御つきの更新。期待バージョンが一致する行だけを更新し、
// 影響行数を返す。0 行なら版が食い違っている（＝衝突）ことを意味する。
func (q *Queries) UpdateStockItem(ctx context.Context, arg UpdateStockItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStockItem,
		arg.Available,
		arg.Version,
		arg.Sku,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
