// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type OrderingEvent struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
	RecordedAt  pgtype.Timestamptz
}

type OrderingOrder struct {
	ID             string
	CustomerID     string
	Status         string
	TotalAmount    int64
	TotalCurrency  string
	ReservationRef string
	Version        int32
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type OrderingOrderLine struct {
	OrderID   string
	LineNo    int32
	Sku       string
	Quantity  int32
	UnitPrice int64
	Currency  string
}

type OrderingOutbox struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}
