// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOrderByID = `-- name: GetOrderByID :one

SELECT id, customer_id, status, total_amount, total_currency, reservation_ref, version
FROM ordering.orders
WHERE id = $1
`

type GetOrderByIDRow struct {
	ID             string
	CustomerID     string
	Status         string
	TotalAmount    int64
	TotalCurrency  string
	ReservationRef string
	Version        int32
}

// sqlc の入力となる SQL 定義。ここから型安全な Go コードを生成する。
// 生成物はコミットし、手で編集しない。クエリを変えたいときはこの SQL を編集して再生成する。
// ID で注文を 1 件取得する。存在しなければ pgx.ErrNoRows が返る。
func (q *Queries) GetOrderByID(ctx context.Context, id string) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.Status,
		&i.TotalAmount,
		&i.TotalCurrency,
		&i.ReservationRef,
		&i.Version,
	)
	return i, err
}

const insertOrder = `-- name: InsertOrder :exec
INSERT INTO ordering.orders (id, customer_id, status, total_amount, total_currency, reservation_ref, version)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertOrderParams struct {
	ID             string
	CustomerID     string
	Status         string
	TotalAmount    int64
	TotalCurrency  string
	ReservationRef string
	Version        int32
}

// 注文を新規挿入する（version は 1 から始まる）。
func (q *Queries) InsertOrder(ctx context.Context, arg InsertOrderParams) error {
	_, err := q.db.Exec(ctx, insertOrder,
		arg.ID,
		arg.CustomerID,
		arg.Status,
		arg.TotalAmount,
		arg.TotalCurrency,
		arg.ReservationRef,
		arg.Version,
	)
	return err
}

const insertOrderLine = `-- name: InsertOrderLine :exec
INSERT INTO ordering.order_lines (order_id, line_no, sku, quantity, unit_price, currency)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertOrderLineParams struct {
	OrderID   string
	LineNo    int32
	Sku       string
	Quantity  int32
	UnitPrice int64
	Currency  string
}

// 注文明細を 1 件挿入する。
func (q *Queries) InsertOrderLine(ctx context.Context, arg InsertOrderLineParams) error {
	_, err := q.db.Exec(ctx, insertOrderLine,
		arg.OrderID,
		arg.LineNo,
		arg.Sku,
		arg.Quantity,
		arg.UnitPrice,
		arg.Currency,
	)
	return err
}

const insertOutboxMessage = `-- name: InsertOutboxMessage :exec
INSERT INTO ordering.outbox (id, message_type, payload, trace_id, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxMessageParams struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}

// アウトボックスへメッセージを積む（集約書き込みと同一トランザクションで実行する）。
func (q *Queries) InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error {
	_, err := q.db.Exec(ctx, insertOutboxMessage,
		arg.ID,
		arg.MessageType,
		arg.Payload,
		arg.TraceID,
		arg.OccurredAt,
	)
	return err
}

const listOrderLines = `-- name: ListOrderLines :many
SELECT order_id, line_no, sku, quantity, unit_price, currency
FROM ordering.order_lines
WHERE order_id = $1
ORDER BY line_no ASC
`

// 注文が保持する明細を行番号順に取得する。
func (q *Queries) ListOrderLines(ctx context.Context, orderID string) ([]OrderingOrderLine, error) {
	rows, err := q.db.Query(ctx, listOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OrderingOrderLine{}
	for rows.Next() {
		var i OrderingOrderLine
		if err := rows.Scan(
			&i.OrderID,
			&i.LineNo,
			&i.Sku,
			&i.Quantity,
			&i.UnitPrice,
			&i.Currency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnpublishedOutbox = `-- name: ListUnpublishedOutbox :many
SELECT id, message_type, payload, trace_id, occurred_at
FROM ordering.outbox
WHERE published_at IS NULL
ORDER BY occurred_at ASC
LIMIT $1
`

type ListUnpublishedOutboxRow struct {
	ID          string
	MessageType string
	Payload     []byte
	TraceID     string
	OccurredAt  pgtype.Timestamptz
}

// 未送信のメッセージを occurred_at 昇順で最大 $1 件取得する。
func (q *Queries) ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error) {
	rows, err := q.db.Query(ctx, listUnpublishedOutbox, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnpublishedOutboxRow{}
	for rows.Next() {
		var i ListUnpublishedOutboxRow
		if err := rows.Scan(
			&i.ID,
			&i.MessageType,
			&i.Payload,
			&i.TraceID,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOutboxPublished = `-- name: MarkOutboxPublished :exec
UPDATE ordering.outbox
SET published_at = now()
WHERE id = $1
`

// 指定 ID のメッセージを送信済みとして記録する。
func (q *Queries) MarkOutboxPublished(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, markOutboxPublished, id)
	return err
}

const updateOrder = `-- name: UpdateOrder :execrows
UPDATE ordering.orders
SET status = $1, version = $2, updated_at = now()
WHERE id = $3 AND version = $4
`

type UpdateOrderParams struct {
	Status    string
	Version   int32
	ID        string
	Version_2 int32
}

// 楽観的排他制御つきの更新。期待バージョンが一致する行だけを更新し、影響行数を返す。
// 0 行なら版が食い違っている（＝衝突）ことを意味する。注文の可変部分は状態のみ。
func (q *Queries) UpdateOrder(ctx context.Context, arg UpdateOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrder,
		arg.Status,
		arg.Version,
		arg.ID,
		arg.Version_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
