// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"context"
)

type Querier interface {
	// sqlc の入力となる SQL 定義。ここから型安全な Go コードを生成する。
	// 生成物はコミットし、手で編集しない。クエリを変えたいときはこの SQL を編集して再生成する。
	// ID で注文を 1 件取得する。存在しなければ pgx.ErrNoRows が返る。
	GetOrderByID(ctx context.Context, id string) (GetOrderByIDRow, error)
	// 注文を新規挿入する（version は 1 から始まる）。
	InsertOrder(ctx context.Context, arg InsertOrderParams) error
	// 注文明細を 1 件挿入する。
	InsertOrderLine(ctx context.Context, arg InsertOrderLineParams) error
	// アウトボックスへメッセージを積む（集約書き込みと同一トランザクションで実行する）。
	InsertOutboxMessage(ctx context.Context, arg InsertOutboxMessageParams) error
	// 注文が保持する明細を行番号順に取得する。
	ListOrderLines(ctx context.Context, orderID string) ([]OrderingOrderLine, error)
	// 未送信のメッセージを occurred_at 昇順で最大 $1 件取得する。
	ListUnpublishedOutbox(ctx context.Context, limit int32) ([]ListUnpublishedOutboxRow, error)
	// 指定 ID のメッセージを送信済みとして記録する。
	MarkOutboxPublished(ctx context.Context, id string) error
	// 楽観的排他制御つきの更新。期待バージョンが一致する行だけを更新し、影響行数を返す。
	// 0 行なら版が食い違っている（＝衝突）ことを意味する。注文の可変部分は状態のみ。
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (int64, error)
}

var _ Querier = (*Queries)(nil)
