// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// GetStock implements getStock operation.
	//
	// 指定した SKU の現在の在庫状態を返す。.
	//
	// GET /stock/{sku}
	GetStock(ctx context.Context, params GetStockParams) (GetStockRes, error)
	// ReplenishStock implements replenishStock operation.
	//
	// 指定した SKU の在庫を補充する。SKU
	// が未登録の場合は新規に作成してから補充する。.
	//
	// POST /stock/{sku}/replenish
	ReplenishStock(ctx context.Context, req *ReplenishRequest, params ReplenishStockParams) (ReplenishStockRes, error)
	// NewError creates *ProblemResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
