// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetStock implements getStock operation.
//
// 指定した SKU の現在の在庫状態を返す。.
//
// GET /stock/{sku}
func (UnimplementedHandler) GetStock(ctx context.Context, params GetStockParams) (r *StockView, _ error) {
	return r, ht.ErrNotImplemented
}

// ReplenishStock implements replenishStock operation.
//
// 指定した SKU の在庫を補充する。SKU
// が未登録の場合は新規に作成してから補充する。.
//
// POST /stock/{sku}/replenish
func (UnimplementedHandler) ReplenishStock(ctx context.Context, req *ReplenishRequest, params ReplenishStockParams) (r *StockView, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemResponseStatusCode) {
	r = new(ProblemResponseStatusCode)
	return r
}
