// Code generated by ogen, DO NOT EDIT.

package openapiinternal

import (
	"fmt"
	"net/url"
	"time"
)

func (s *ProblemResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// Ref: #/components/schemas/Ack
type Ack struct {
	// 処理結果（例 accepted）.
	Status string `json:"status"`
}

// GetStatus returns the value of Status.
func (s *Ack) GetStatus() string {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *Ack) SetStatus(val string) {
	s.Status = val
}

// アウトボックスの受信メッセージ封筒.
// Ref: #/components/schemas/InboundMessage
type InboundMessage struct {
	// メッセージの一意な識別子.
	ID string `json:"id"`
	// Message_type（Consumer を選択する種別）.
	Type string `json:"type"`
	// 翻訳済み契約のシリアライズ（JSON 文字列）.
	Payload string `json:"payload"`
	// Seam を跨ぐ相関 ID.
	TraceID OptString `json:"trace_id"`
	// メッセージ発生時刻.
	OccurredAt OptDateTime `json:"occurred_at"`
}

// GetID returns the value of ID.
func (s *InboundMessage) GetID() string {
	return s.ID
}

// GetType returns the value of Type.
func (s *InboundMessage) GetType() string {
	return s.Type
}

// GetPayload returns the value of Payload.
func (s *InboundMessage) GetPayload() string {
	return s.Payload
}

// GetTraceID returns the value of TraceID.
func (s *InboundMessage) GetTraceID() OptString {
	return s.TraceID
}

// GetOccurredAt returns the value of OccurredAt.
func (s *InboundMessage) GetOccurredAt() OptDateTime {
	return s.OccurredAt
}

// SetID sets the value of ID.
func (s *InboundMessage) SetID(val string) {
	s.ID = val
}

// SetType sets the value of Type.
func (s *InboundMessage) SetType(val string) {
	s.Type = val
}

// SetPayload sets the value of Payload.
func (s *InboundMessage) SetPayload(val string) {
	s.Payload = val
}

// SetTraceID sets the value of TraceID.
func (s *InboundMessage) SetTraceID(val OptString) {
	s.TraceID = val
}

// SetOccurredAt sets the value of OccurredAt.
func (s *InboundMessage) SetOccurredAt(val OptDateTime) {
	s.OccurredAt = val
}

// NewOptDateTime returns new OptDateTime with value set to v.
func NewOptDateTime(v time.Time) OptDateTime {
	return OptDateTime{
		Value: v,
		Set:   true,
	}
}

// OptDateTime is optional time.Time.
type OptDateTime struct {
	Value time.Time
	Set   bool
}

// IsSet returns true if OptDateTime was set.
func (o OptDateTime) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDateTime) Reset() {
	var v time.Time
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDateTime) SetTo(v time.Time) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDateTime) Get() (v time.Time, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDateTime) Or(d time.Time) time.Time {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// RFC 9457 (Problem Details for HTTP APIs) に準拠したエラー表現.
// Ref: #/components/schemas/ProblemDetails
type ProblemDetails struct {
	// 問題の種別を示す URI。既定は "about:blank"。.
	Type url.URL `json:"type"`
	// 問題種別の短い人間可読な要約.
	Title string `json:"title"`
	// HTTP ステータスコード.
	Status int `json:"status"`
	// 今回の発生に固有の人間可読な説明.
	Detail OptString `json:"detail"`
	// 問題が発生した具体的なリソースを示す URI.
	Instance OptURI `json:"instance"`
}

// GetType returns the value of Type.
func (s *ProblemDetails) GetType() url.URL {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ProblemDetails) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *ProblemDetails) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *ProblemDetails) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *ProblemDetails) GetInstance() OptURI {
	return s.Instance
}

// SetType sets the value of Type.
func (s *ProblemDetails) SetType(val url.URL) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ProblemDetails) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *ProblemDetails) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *ProblemDetails) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *ProblemDetails) SetInstance(val OptURI) {
	s.Instance = val
}

// ProblemResponseStatusCode wraps ProblemDetails with StatusCode.
type ProblemResponseStatusCode struct {
	StatusCode int
	Response   ProblemDetails
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemResponseStatusCode) GetResponse() ProblemDetails {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemResponseStatusCode) SetResponse(val ProblemDetails) {
	s.Response = val
}

// Ref: #/components/schemas/ReserveCommand
type ReserveCommand struct {
	// 予約参照（不透明な相関 ID）.
	Ref string `json:"ref"`
	// 予約する SKU と数量の一覧.
	Lines []ReserveLine `json:"lines"`
}

// GetRef returns the value of Ref.
func (s *ReserveCommand) GetRef() string {
	return s.Ref
}

// GetLines returns the value of Lines.
func (s *ReserveCommand) GetLines() []ReserveLine {
	return s.Lines
}

// SetRef sets the value of Ref.
func (s *ReserveCommand) SetRef(val string) {
	s.Ref = val
}

// SetLines sets the value of Lines.
func (s *ReserveCommand) SetLines(val []ReserveLine) {
	s.Lines = val
}

// Ref: #/components/schemas/ReserveLine
type ReserveLine struct {
	// 在庫識別子.
	Sku string `json:"sku"`
	// 予約する数量。値の妥当性検証はドメイン層が行う。.
	Quantity int `json:"quantity"`
}

// GetSku returns the value of Sku.
func (s *ReserveLine) GetSku() string {
	return s.Sku
}

// GetQuantity returns the value of Quantity.
func (s *ReserveLine) GetQuantity() int {
	return s.Quantity
}

// SetSku sets the value of Sku.
func (s *ReserveLine) SetSku(val string) {
	s.Sku = val
}

// SetQuantity sets the value of Quantity.
func (s *ReserveLine) SetQuantity(val int) {
	s.Quantity = val
}
