// Code generated by ogen, DO NOT EDIT.

package openapiinternal

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// ConfirmReservation implements confirmReservation operation.
//
// 指定参照の予約を確定する。有効な予約が無ければ 404 を返す。.
//
// POST /reservations/{ref}/confirm
func (UnimplementedHandler) ConfirmReservation(ctx context.Context, params ConfirmReservationParams) (r *Ack, _ error) {
	return r, ht.ErrNotImplemented
}

// IngestEvent implements ingestEvent operation.
//
// 受信したメッセージを outbox.Router へ委譲し、message_type に応じた Consumer
// が処理する。 未登録の種別は 422 を返す（黙って捨てない）。payload
// は翻訳済み契約のシリアライズ（JSON 文字列）。.
//
// POST /events
func (UnimplementedHandler) IngestEvent(ctx context.Context, req *InboundMessage) (r *Ack, _ error) {
	return r, ht.ErrNotImplemented
}

// ReleaseReservation implements releaseReservation operation.
//
// 指定参照の予約を解放して在庫を戻す。未知・解放済みの参照でも冪等に成功する。.
//
// POST /reservations/{ref}/release
func (UnimplementedHandler) ReleaseReservation(ctx context.Context, params ReleaseReservationParams) (r *Ack, _ error) {
	return r, ht.ErrNotImplemented
}

// ReserveStock implements reserveStock operation.
//
// 1 つの予約参照に対して複数 SKU をまとめて仮予約する。1
// つでも在庫不足なら全体を失敗させる。.
//
// POST /reservations
func (UnimplementedHandler) ReserveStock(ctx context.Context, req *ReserveCommand) (r *Ack, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemResponseStatusCode) {
	r = new(ProblemResponseStatusCode)
	return r
}
