// Code generated by ogen, DO NOT EDIT.

package openapiinternal

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// ConfirmReservationParams is parameters of confirmReservation operation.
type ConfirmReservationParams struct {
	// 予約参照（不透明な相関 ID）.
	Ref string
}

func unpackConfirmReservationParams(packed middleware.Parameters) (params ConfirmReservationParams) {
	{
		key := middleware.ParameterKey{
			Name: "ref",
			In:   "path",
		}
		params.Ref = packed[key].(string)
	}
	return params
}

func decodeConfirmReservationParams(args [1]string, argsEscaped bool, r *http.Request) (params ConfirmReservationParams, _ error) {
	// Decode path: ref.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ref",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ref = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Ref)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ref",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}

// ReleaseReservationParams is parameters of releaseReservation operation.
type ReleaseReservationParams struct {
	// 予約参照（不透明な相関 ID）.
	Ref string
}

func unpackReleaseReservationParams(packed middleware.Parameters) (params ReleaseReservationParams) {
	{
		key := middleware.ParameterKey{
			Name: "ref",
			In:   "path",
		}
		params.Ref = packed[key].(string)
	}
	return params
}

func decodeReleaseReservationParams(args [1]string, argsEscaped bool, r *http.Request) (params ReleaseReservationParams, _ error) {
	// Decode path: ref.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "ref",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToString(val)
				if err != nil {
					return err
				}

				params.Ref = c
				return nil
			}(); err != nil {
				return err
			}
			if err := func() error {
				if err := (validate.String{
					MinLength:     1,
					MinLengthSet:  true,
					MaxLength:     0,
					MaxLengthSet:  false,
					Email:         false,
					Hostname:      false,
					Regex:         nil,
					MinNumeric:    0,
					MinNumericSet: false,
					MaxNumeric:    0,
					MaxNumericSet: false,
				}).Validate(string(params.Ref)); err != nil {
					return errors.Wrap(err, "string")
				}
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "ref",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
