// Code generated by ogen, DO NOT EDIT.

package openapiinternal

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// ConfirmReservation implements confirmReservation operation.
	//
	// 指定参照の予約を確定する。有効な予約が無ければ 404 を返す。.
	//
	// POST /reservations/{ref}/confirm
	ConfirmReservation(ctx context.Context, params ConfirmReservationParams) (*Ack, error)
	// IngestEvent implements ingestEvent operation.
	//
	// 受信したメッセージを outbox.Router へ委譲し、message_type に応じた Consumer
	// が処理する。 未登録の種別は 422 を返す（黙って捨てない）。payload
	// は翻訳済み契約のシリアライズ（JSON 文字列）。.
	//
	// POST /events
	IngestEvent(ctx context.Context, req *InboundMessage) (*Ack, error)
	// ReleaseReservation implements releaseReservation operation.
	//
	// 指定参照の予約を解放して在庫を戻す。未知・解放済みの参照でも冪等に成功する。.
	//
	// POST /reservations/{ref}/release
	ReleaseReservation(ctx context.Context, params ReleaseReservationParams) (*Ack, error)
	// ReserveStock implements reserveStock operation.
	//
	// 1 つの予約参照に対して複数 SKU をまとめて仮予約する。1
	// つでも在庫不足なら全体を失敗させる。.
	//
	// POST /reservations
	ReserveStock(ctx context.Context, req *ReserveCommand) (*Ack, error)
	// NewError creates *ProblemResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
