// Code generated by ogen, DO NOT EDIT.

package openapiinternal

// OperationName is the ogen operation name
type OperationName = string

const (
	ConfirmReservationOperation OperationName = "ConfirmReservation"
	IngestEventOperation        OperationName = "IngestEvent"
	ReleaseReservationOperation OperationName = "ReleaseReservation"
	ReserveStockOperation       OperationName = "ReserveStock"
)
