// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Probe implements probe operation.
//
// 抽出テスト用のエンドポイント.
//
// POST /probe
func (UnimplementedHandler) Probe(ctx context.Context, req *Probe, params ProbeParams) (r *Ack, _ error) {
	return r, ht.ErrNotImplemented
}
