// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/Ack
type Ack struct {
	Ok bool `json:"ok"`
}

// GetOk returns the value of Ok.
func (s *Ack) GetOk() bool {
	return s.Ok
}

// SetOk sets the value of Ok.
func (s *Ack) SetOk(val bool) {
	s.Ok = val
}

// Ref: #/components/schemas/Line
type Line struct {
	Sku      string   `json:"sku"`
	Quantity int      `json:"quantity"`
	Price    OptPrice `json:"price"`
}

// GetSku returns the value of Sku.
func (s *Line) GetSku() string {
	return s.Sku
}

// GetQuantity returns the value of Quantity.
func (s *Line) GetQuantity() int {
	return s.Quantity
}

// GetPrice returns the value of Price.
func (s *Line) GetPrice() OptPrice {
	return s.Price
}

// SetSku sets the value of Sku.
func (s *Line) SetSku(val string) {
	s.Sku = val
}

// SetQuantity sets the value of Quantity.
func (s *Line) SetQuantity(val int) {
	s.Quantity = val
}

// SetPrice sets the value of Price.
func (s *Line) SetPrice(val OptPrice) {
	s.Price = val
}

// Ref: #/components/schemas/Nested
type Nested struct {
	Inner string `json:"inner"`
}

// GetInner returns the value of Inner.
func (s *Nested) GetInner() string {
	return s.Inner
}

// SetInner sets the value of Inner.
func (s *Nested) SetInner(val string) {
	s.Inner = val
}

// NewOptPrice returns new OptPrice with value set to v.
func NewOptPrice(v Price) OptPrice {
	return OptPrice{
		Value: v,
		Set:   true,
	}
}

// OptPrice is optional Price.
type OptPrice struct {
	Value Price
	Set   bool
}

// IsSet returns true if OptPrice was set.
func (o OptPrice) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptPrice) Reset() {
	var v Price
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptPrice) SetTo(v Price) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptPrice) Get() (v Price, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptPrice) Or(d Price) Price {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptProbeKind returns new OptProbeKind with value set to v.
func NewOptProbeKind(v ProbeKind) OptProbeKind {
	return OptProbeKind{
		Value: v,
		Set:   true,
	}
}

// OptProbeKind is optional ProbeKind.
type OptProbeKind struct {
	Value ProbeKind
	Set   bool
}

// IsSet returns true if OptProbeKind was set.
func (o OptProbeKind) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptProbeKind) Reset() {
	var v ProbeKind
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptProbeKind) SetTo(v ProbeKind) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptProbeKind) Get() (v ProbeKind, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptProbeKind) Or(d ProbeKind) ProbeKind {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/Price
type Price struct {
	Amount   int    `json:"amount"`
	Currency string `json:"currency"`
}

// GetAmount returns the value of Amount.
func (s *Price) GetAmount() int {
	return s.Amount
}

// GetCurrency returns the value of Currency.
func (s *Price) GetCurrency() string {
	return s.Currency
}

// SetAmount sets the value of Amount.
func (s *Price) SetAmount(val int) {
	s.Amount = val
}

// SetCurrency sets the value of Currency.
func (s *Price) SetCurrency(val string) {
	s.Currency = val
}

// Ref: #/components/schemas/Probe
type Probe struct {
	Name   string       `json:"name"`
	Kind   OptProbeKind `json:"kind"`
	Tags   []string     `json:"tags"`
	Lines  []Line       `json:"lines"`
	Nested Nested       `json:"nested"`
}

// GetName returns the value of Name.
func (s *Probe) GetName() string {
	return s.Name
}

// GetKind returns the value of Kind.
func (s *Probe) GetKind() OptProbeKind {
	return s.Kind
}

// GetTags returns the value of Tags.
func (s *Probe) GetTags() []string {
	return s.Tags
}

// GetLines returns the value of Lines.
func (s *Probe) GetLines() []Line {
	return s.Lines
}

// GetNested returns the value of Nested.
func (s *Probe) GetNested() Nested {
	return s.Nested
}

// SetName sets the value of Name.
func (s *Probe) SetName(val string) {
	s.Name = val
}

// SetKind sets the value of Kind.
func (s *Probe) SetKind(val OptProbeKind) {
	s.Kind = val
}

// SetTags sets the value of Tags.
func (s *Probe) SetTags(val []string) {
	s.Tags = val
}

// SetLines sets the value of Lines.
func (s *Probe) SetLines(val []Line) {
	s.Lines = val
}

// SetNested sets the value of Nested.
func (s *Probe) SetNested(val Nested) {
	s.Nested = val
}

type ProbeKind string

const (
	ProbeKindAlpha ProbeKind = "alpha"
	ProbeKindBeta  ProbeKind = "beta"
)

// AllValues returns all ProbeKind values.
func (ProbeKind) AllValues() []ProbeKind {
	return []ProbeKind{
		ProbeKindAlpha,
		ProbeKindBeta,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s ProbeKind) MarshalText() ([]byte, error) {
	switch s {
	case ProbeKindAlpha:
		return []byte(s), nil
	case ProbeKindBeta:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *ProbeKind) UnmarshalText(data []byte) error {
	switch ProbeKind(data) {
	case ProbeKindAlpha:
		*s = ProbeKindAlpha
		return nil
	case ProbeKindBeta:
		*s = ProbeKindBeta
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
