// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"net/http"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
)

// ProbeParams is parameters of probe operation.
type ProbeParams struct {
	Attempt int
}

func unpackProbeParams(packed middleware.Parameters) (params ProbeParams) {
	{
		key := middleware.ParameterKey{
			Name: "attempt",
			In:   "query",
		}
		params.Attempt = packed[key].(int)
	}
	return params
}

func decodeProbeParams(args [0]string, argsEscaped bool, r *http.Request) (params ProbeParams, _ error) {
	q := uri.NewQueryDecoder(r.URL.Query())
	// Decode query: attempt.
	if err := func() error {
		cfg := uri.QueryParameterDecodingConfig{
			Name:    "attempt",
			Style:   uri.QueryStyleForm,
			Explode: true,
		}

		if err := q.HasParam(cfg); err == nil {
			if err := q.DecodeParam(cfg, func(d uri.Decoder) error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToInt(val)
				if err != nil {
					return err
				}

				params.Attempt = c
				return nil
			}); err != nil {
				return err
			}
		} else {
			return err
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "attempt",
			In:   "query",
			Err:  err,
		}
	}
	return params, nil
}
