// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/example/go-ddd-template/contexts/inventory/internal/application (interfaces: StockStore,MessagePublisher,Clock,EventDispatcher,Repos)
//
// Generated by this command:
//
//	mockgen -typed -destination mock_application.go -package mock github.com/example/go-ddd-template/contexts/inventory/internal/application StockStore,MessagePublisher,Clock,EventDispatcher,Repos
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	application "github.com/example/go-ddd-template/contexts/inventory/internal/application"
	domain "github.com/example/go-ddd-template/contexts/inventory/internal/domain"
	outbox "github.com/example/go-ddd-template/shared/outbox"
	gomock "go.uber.org/mock/gomock"
)

// MockStockStore is a mock of StockStore interface.
type MockStockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStockStoreMockRecorder
	isgomock struct{}
}

// MockStockStoreMockRecorder is the mock recorder for MockStockStore.
type MockStockStoreMockRecorder struct {
	mock *MockStockStore
}

// NewMockStockStore creates a new mock instance.
func NewMockStockStore(ctrl *gomock.Controller) *MockStockStore {
	mock := &MockStockStore{ctrl: ctrl}
	mock.recorder = &MockStockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStockStore) EXPECT() *MockStockStoreMockRecorder {
	return m.recorder
}

// Load mocks base method.
func (m *MockStockStore) Load(ctx context.Context, sku domain.SKU) (*domain.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load", ctx, sku)
	ret0, _ := ret[0].(*domain.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockStockStoreMockRecorder) Load(ctx, sku any) *MockStockStoreLoadCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockStockStore)(nil).Load), ctx, sku)
	return &MockStockStoreLoadCall{Call: call}
}

// MockStockStoreLoadCall wrap *gomock.Call
type MockStockStoreLoadCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockStoreLoadCall) Return(arg0 *domain.StockItem, arg1 error) *MockStockStoreLoadCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockStoreLoadCall) Do(f func(context.Context, domain.SKU) (*domain.StockItem, error)) *MockStockStoreLoadCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockStoreLoadCall) DoAndReturn(f func(context.Context, domain.SKU) (*domain.StockItem, error)) *MockStockStoreLoadCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadByReservation mocks base method.
func (m *MockStockStore) LoadByReservation(ctx context.Context, ref domain.ReservationRef) ([]*domain.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadByReservation", ctx, ref)
	ret0, _ := ret[0].([]*domain.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadByReservation indicates an expected call of LoadByReservation.
func (mr *MockStockStoreMockRecorder) LoadByReservation(ctx, ref any) *MockStockStoreLoadByReservationCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadByReservation", reflect.TypeOf((*MockStockStore)(nil).LoadByReservation), ctx, ref)
	return &MockStockStoreLoadByReservationCall{Call: call}
}

// MockStockStoreLoadByReservationCall wrap *gomock.Call
type MockStockStoreLoadByReservationCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockStoreLoadByReservationCall) Return(arg0 []*domain.StockItem, arg1 error) *MockStockStoreLoadByReservationCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockStoreLoadByReservationCall) Do(f func(context.Context, domain.ReservationRef) ([]*domain.StockItem, error)) *MockStockStoreLoadByReservationCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockStoreLoadByReservationCall) DoAndReturn(f func(context.Context, domain.ReservationRef) ([]*domain.StockItem, error)) *MockStockStoreLoadByReservationCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadExpiredPending mocks base method.
func (m *MockStockStore) LoadExpiredPending(ctx context.Context, before time.Time, limit int) ([]*domain.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadExpiredPending", ctx, before, limit)
	ret0, _ := ret[0].([]*domain.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadExpiredPending indicates an expected call of LoadExpiredPending.
func (mr *MockStockStoreMockRecorder) LoadExpiredPending(ctx, before, limit any) *MockStockStoreLoadExpiredPendingCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadExpiredPending", reflect.TypeOf((*MockStockStore)(nil).LoadExpiredPending), ctx, before, limit)
	return &MockStockStoreLoadExpiredPendingCall{Call: call}
}

// MockStockStoreLoadExpiredPendingCall wrap *gomock.Call
type MockStockStoreLoadExpiredPendingCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockStoreLoadExpiredPendingCall) Return(arg0 []*domain.StockItem, arg1 error) *MockStockStoreLoadExpiredPendingCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockStoreLoadExpiredPendingCall) Do(f func(context.Context, time.Time, int) ([]*domain.StockItem, error)) *MockStockStoreLoadExpiredPendingCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockStoreLoadExpiredPendingCall) DoAndReturn(f func(context.Context, time.Time, int) ([]*domain.StockItem, error)) *MockStockStoreLoadExpiredPendingCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// LoadMany mocks base method.
func (m *MockStockStore) LoadMany(ctx context.Context, skus []domain.SKU) ([]*domain.StockItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadMany", ctx, skus)
	ret0, _ := ret[0].([]*domain.StockItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadMany indicates an expected call of LoadMany.
func (mr *MockStockStoreMockRecorder) LoadMany(ctx, skus any) *MockStockStoreLoadManyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadMany", reflect.TypeOf((*MockStockStore)(nil).LoadMany), ctx, skus)
	return &MockStockStoreLoadManyCall{Call: call}
}

// MockStockStoreLoadManyCall wrap *gomock.Call
type MockStockStoreLoadManyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockStoreLoadManyCall) Return(arg0 []*domain.StockItem, arg1 error) *MockStockStoreLoadManyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockStoreLoadManyCall) Do(f func(context.Context, []domain.SKU) ([]*domain.StockItem, error)) *MockStockStoreLoadManyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockStoreLoadManyCall) DoAndReturn(f func(context.Context, []domain.SKU) ([]*domain.StockItem, error)) *MockStockStoreLoadManyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockStockStore) Save(ctx context.Context, items ...*domain.StockItem) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range items {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Save", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStockStoreMockRecorder) Save(ctx any, items ...any) *MockStockStoreSaveCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, items...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStockStore)(nil).Save), varargs...)
	return &MockStockStoreSaveCall{Call: call}
}

// MockStockStoreSaveCall wrap *gomock.Call
type MockStockStoreSaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockStockStoreSaveCall) Return(arg0 error) *MockStockStoreSaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockStockStoreSaveCall) Do(f func(context.Context, ...*domain.StockItem) error) *MockStockStoreSaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockStockStoreSaveCall) DoAndReturn(f func(context.Context, ...*domain.StockItem) error) *MockStockStoreSaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockMessagePublisher is a mock of MessagePublisher interface.
type MockMessagePublisher struct {
	ctrl     *gomock.Controller
	recorder *MockMessagePublisherMockRecorder
	isgomock struct{}
}

// MockMessagePublisherMockRecorder is the mock recorder for MockMessagePublisher.
type MockMessagePublisherMockRecorder struct {
	mock *MockMessagePublisher
}

// NewMockMessagePublisher creates a new mock instance.
func NewMockMessagePublisher(ctrl *gomock.Controller) *MockMessagePublisher {
	mock := &MockMessagePublisher{ctrl: ctrl}
	mock.recorder = &MockMessagePublisherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMessagePublisher) EXPECT() *MockMessagePublisherMockRecorder {
	return m.recorder
}

// Enqueue mocks base method.
func (m_2 *MockMessagePublisher) Enqueue(ctx context.Context, m outbox.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Enqueue", ctx, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockMessagePublisherMockRecorder) Enqueue(ctx, m any) *MockMessagePublisherEnqueueCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockMessagePublisher)(nil).Enqueue), ctx, m)
	return &MockMessagePublisherEnqueueCall{Call: call}
}

// MockMessagePublisherEnqueueCall wrap *gomock.Call
type MockMessagePublisherEnqueueCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockMessagePublisherEnqueueCall) Return(arg0 error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockMessagePublisherEnqueueCall) Do(f func(context.Context, outbox.Message) error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockMessagePublisherEnqueueCall) DoAndReturn(f func(context.Context, outbox.Message) error) *MockMessagePublisherEnqueueCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockClock is a mock of Clock interface.
type MockClock struct {
	ctrl     *gomock.Controller
	recorder *MockClockMockRecorder
	isgomock struct{}
}

// MockClockMockRecorder is the mock recorder for MockClock.
type MockClockMockRecorder struct {
	mock *MockClock
}

// NewMockClock creates a new mock instance.
func NewMockClock(ctrl *gomock.Controller) *MockClock {
	mock := &MockClock{ctrl: ctrl}
	mock.recorder = &MockClockMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClock) EXPECT() *MockClockMockRecorder {
	return m.recorder
}

// Now mocks base method.
func (m *MockClock) Now() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Now")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// Now indicates an expected call of Now.
func (mr *MockClockMockRecorder) Now() *MockClockNowCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Now", reflect.TypeOf((*MockClock)(nil).Now))
	return &MockClockNowCall{Call: call}
}

// MockClockNowCall wrap *gomock.Call
type MockClockNowCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockClockNowCall) Return(arg0 time.Time) *MockClockNowCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockClockNowCall) Do(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockClockNowCall) DoAndReturn(f func() time.Time) *MockClockNowCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockEventDispatcher is a mock of EventDispatcher interface.
type MockEventDispatcher struct {
	ctrl     *gomock.Controller
	recorder *MockEventDispatcherMockRecorder
	isgomock struct{}
}

// MockEventDispatcherMockRecorder is the mock recorder for MockEventDispatcher.
type MockEventDispatcherMockRecorder struct {
	mock *MockEventDispatcher
}

// NewMockEventDispatcher creates a new mock instance.
func NewMockEventDispatcher(ctrl *gomock.Controller) *MockEventDispatcher {
	mock := &MockEventDispatcher{ctrl: ctrl}
	mock.recorder = &MockEventDispatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventDispatcher) EXPECT() *MockEventDispatcherMockRecorder {
	return m.recorder
}

// Dispatch mocks base method.
func (m *MockEventDispatcher) Dispatch(ctx context.Context, events ...domain.DomainEvent) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range events {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Dispatch", varargs...)
}

// Dispatch indicates an expected call of Dispatch.
func (mr *MockEventDispatcherMockRecorder) Dispatch(ctx any, events ...any) *MockEventDispatcherDispatchCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, events...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dispatch", reflect.TypeOf((*MockEventDispatcher)(nil).Dispatch), varargs...)
	return &MockEventDispatcherDispatchCall{Call: call}
}

// MockEventDispatcherDispatchCall wrap *gomock.Call
type MockEventDispatcherDispatchCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockEventDispatcherDispatchCall) Return() *MockEventDispatcherDispatchCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockEventDispatcherDispatchCall) Do(f func(context.Context, ...domain.DomainEvent)) *MockEventDispatcherDispatchCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockEventDispatcherDispatchCall) DoAndReturn(f func(context.Context, ...domain.DomainEvent)) *MockEventDispatcherDispatchCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockRepos is a mock of Repos interface.
type MockRepos struct {
	ctrl     *gomock.Controller
	recorder *MockReposMockRecorder
	isgomock struct{}
}

// MockReposMockRecorder is the mock recorder for MockRepos.
type MockReposMockRecorder struct {
	mock *MockRepos
}

// NewMockRepos creates a new mock instance.
func NewMockRepos(ctrl *gomock.Controller) *MockRepos {
	mock := &MockRepos{ctrl: ctrl}
	mock.recorder = &MockReposMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepos) EXPECT() *MockReposMockRecorder {
	return m.recorder
}

// Outbox mocks base method.
func (m *MockRepos) Outbox() application.MessagePublisher {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Outbox")
	ret0, _ := ret[0].(application.MessagePublisher)
	return ret0
}

// Outbox indicates an expected call of Outbox.
func (mr *MockReposMockRecorder) Outbox() *MockReposOutboxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Outbox", reflect.TypeOf((*MockRepos)(nil).Outbox))
	return &MockReposOutboxCall{Call: call}
}

// MockReposOutboxCall wrap *gomock.Call
type MockReposOutboxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReposOutboxCall) Return(arg0 application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReposOutboxCall) Do(f func() application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReposOutboxCall) DoAndReturn(f func() application.MessagePublisher) *MockReposOutboxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stock mocks base method.
func (m *MockRepos) Stock() application.StockStore {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stock")
	ret0, _ := ret[0].(application.StockStore)
	return ret0
}

// Stock indicates an expected call of Stock.
func (mr *MockReposMockRecorder) Stock() *MockReposStockCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stock", reflect.TypeOf((*MockRepos)(nil).Stock))
	return &MockReposStockCall{Call: call}
}

// MockReposStockCall wrap *gomock.Call
type MockReposStockCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReposStockCall) Return(arg0 application.StockStore) *MockReposStockCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReposStockCall) Do(f func() application.StockStore) *MockReposStockCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReposStockCall) DoAndReturn(f func() application.StockStore) *MockReposStockCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
