// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"
	"net/url"
)

func (s *ProblemResponseStatusCode) Error() string {
	return fmt.Sprintf("code %d: %+v", s.StatusCode, s.Response)
}

// 1 件のフィールド違反。RFC 9457 の拡張メンバー invalid-params の要素。.
// Ref: #/components/schemas/InvalidParam
type InvalidParam struct {
	// 違反したフィールドのパス（ドット + 角括弧記法）。
	// 契約検証（400）では配列添字は付かない。ドメイン検証（422）では付く。
	// クライアントは添字の有無に依存した解析をしてはならない。.
	Name string `json:"name"`
	// 機械可読な違反理由。語彙は type によって決まる （validation-error
	// なら契約検証語彙、invalid-input ならドメイン検証語彙）。.
	Code string `json:"code"`
	// 人間可読な説明。code から導出される定型文であり、受信値を含まない。.
	Reason OptString `json:"reason"`
}

// GetName returns the value of Name.
func (s *InvalidParam) GetName() string {
	return s.Name
}

// GetCode returns the value of Code.
func (s *InvalidParam) GetCode() string {
	return s.Code
}

// GetReason returns the value of Reason.
func (s *InvalidParam) GetReason() OptString {
	return s.Reason
}

// SetName sets the value of Name.
func (s *InvalidParam) SetName(val string) {
	s.Name = val
}

// SetCode sets the value of Code.
func (s *InvalidParam) SetCode(val string) {
	s.Code = val
}

// SetReason sets the value of Reason.
func (s *InvalidParam) SetReason(val OptString) {
	s.Reason = val
}

// 金額。最小通貨単位（例 円・セント）の整数と ISO-4217
// 通貨コードで表す。.
// Ref: #/components/schemas/Money
type Money struct {
	// 最小通貨単位での金額。非負であること（検証はドメイン層）。.
	Amount int64 `json:"amount"`
	// ISO-4217 の通貨コード（例 JPY, USD）。.
	Currency string `json:"currency"`
}

// GetAmount returns the value of Amount.
func (s *Money) GetAmount() int64 {
	return s.Amount
}

// GetCurrency returns the value of Currency.
func (s *Money) GetCurrency() string {
	return s.Currency
}

// SetAmount sets the value of Amount.
func (s *Money) SetAmount(val int64) {
	s.Amount = val
}

// SetCurrency sets the value of Currency.
func (s *Money) SetCurrency(val string) {
	s.Currency = val
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURI returns new OptURI with value set to v.
func NewOptURI(v url.URL) OptURI {
	return OptURI{
		Value: v,
		Set:   true,
	}
}

// OptURI is optional url.URL.
type OptURI struct {
	Value url.URL
	Set   bool
}

// IsSet returns true if OptURI was set.
func (o OptURI) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURI) Reset() {
	var v url.URL
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURI) SetTo(v url.URL) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURI) Get() (v url.URL, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURI) Or(d url.URL) url.URL {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/OrderLineView
type OrderLineView struct {
	// 在庫識別子.
	Sku string `json:"sku"`
	// 注文数量.
	Quantity  int   `json:"quantity"`
	UnitPrice Money `json:"unitPrice"`
	Subtotal  Money `json:"subtotal"`
}

// GetSku returns the value of Sku.
func (s *OrderLineView) GetSku() string {
	return s.Sku
}

// GetQuantity returns the value of Quantity.
func (s *OrderLineView) GetQuantity() int {
	return s.Quantity
}

// GetUnitPrice returns the value of UnitPrice.
func (s *OrderLineView) GetUnitPrice() Money {
	return s.UnitPrice
}

// GetSubtotal returns the value of Subtotal.
func (s *OrderLineView) GetSubtotal() Money {
	return s.Subtotal
}

// SetSku sets the value of Sku.
func (s *OrderLineView) SetSku(val string) {
	s.Sku = val
}

// SetQuantity sets the value of Quantity.
func (s *OrderLineView) SetQuantity(val int) {
	s.Quantity = val
}

// SetUnitPrice sets the value of UnitPrice.
func (s *OrderLineView) SetUnitPrice(val Money) {
	s.UnitPrice = val
}

// SetSubtotal sets the value of Subtotal.
func (s *OrderLineView) SetSubtotal(val Money) {
	s.Subtotal = val
}

// Ref: #/components/schemas/OrderView
type OrderView struct {
	// 注文の識別子.
	ID string `json:"id"`
	// 注文者（顧客）の識別子.
	CustomerId string `json:"customerId"`
	// 注文状態（confirmed / cancelled）.
	Status string          `json:"status"`
	Lines  []OrderLineView `json:"lines"`
	Total  Money           `json:"total"`
	// この注文が在庫予約に用いた予約参照（相関 ID）.
	ReservationRef string `json:"reservationRef"`
	// 楽観的排他制御のためのバージョン番号.
	Version int `json:"version"`
}

// GetID returns the value of ID.
func (s *OrderView) GetID() string {
	return s.ID
}

// GetCustomerId returns the value of CustomerId.
func (s *OrderView) GetCustomerId() string {
	return s.CustomerId
}

// GetStatus returns the value of Status.
func (s *OrderView) GetStatus() string {
	return s.Status
}

// GetLines returns the value of Lines.
func (s *OrderView) GetLines() []OrderLineView {
	return s.Lines
}

// GetTotal returns the value of Total.
func (s *OrderView) GetTotal() Money {
	return s.Total
}

// GetReservationRef returns the value of ReservationRef.
func (s *OrderView) GetReservationRef() string {
	return s.ReservationRef
}

// GetVersion returns the value of Version.
func (s *OrderView) GetVersion() int {
	return s.Version
}

// SetID sets the value of ID.
func (s *OrderView) SetID(val string) {
	s.ID = val
}

// SetCustomerId sets the value of CustomerId.
func (s *OrderView) SetCustomerId(val string) {
	s.CustomerId = val
}

// SetStatus sets the value of Status.
func (s *OrderView) SetStatus(val string) {
	s.Status = val
}

// SetLines sets the value of Lines.
func (s *OrderView) SetLines(val []OrderLineView) {
	s.Lines = val
}

// SetTotal sets the value of Total.
func (s *OrderView) SetTotal(val Money) {
	s.Total = val
}

// SetReservationRef sets the value of ReservationRef.
func (s *OrderView) SetReservationRef(val string) {
	s.ReservationRef = val
}

// SetVersion sets the value of Version.
func (s *OrderView) SetVersion(val int) {
	s.Version = val
}

// Ref: #/components/schemas/PlaceOrderLine
type PlaceOrderLine struct {
	// 在庫識別子.
	Sku string `json:"sku"`
	// 注文数量。1 以上であること（検証はドメイン層）。.
	Quantity  int   `json:"quantity"`
	UnitPrice Money `json:"unitPrice"`
}

// GetSku returns the value of Sku.
func (s *PlaceOrderLine) GetSku() string {
	return s.Sku
}

// GetQuantity returns the value of Quantity.
func (s *PlaceOrderLine) GetQuantity() int {
	return s.Quantity
}

// GetUnitPrice returns the value of UnitPrice.
func (s *PlaceOrderLine) GetUnitPrice() Money {
	return s.UnitPrice
}

// SetSku sets the value of Sku.
func (s *PlaceOrderLine) SetSku(val string) {
	s.Sku = val
}

// SetQuantity sets the value of Quantity.
func (s *PlaceOrderLine) SetQuantity(val int) {
	s.Quantity = val
}

// SetUnitPrice sets the value of UnitPrice.
func (s *PlaceOrderLine) SetUnitPrice(val Money) {
	s.UnitPrice = val
}

// Ref: #/components/schemas/PlaceOrderRequest
type PlaceOrderRequest struct {
	// 注文者（顧客）の識別子.
	CustomerId string `json:"customerId"`
	// 注文明細（1 行以上）.
	Lines []PlaceOrderLine `json:"lines"`
}

// GetCustomerId returns the value of CustomerId.
func (s *PlaceOrderRequest) GetCustomerId() string {
	return s.CustomerId
}

// GetLines returns the value of Lines.
func (s *PlaceOrderRequest) GetLines() []PlaceOrderLine {
	return s.Lines
}

// SetCustomerId sets the value of CustomerId.
func (s *PlaceOrderRequest) SetCustomerId(val string) {
	s.CustomerId = val
}

// SetLines sets the value of Lines.
func (s *PlaceOrderRequest) SetLines(val []PlaceOrderLine) {
	s.Lines = val
}

// RFC 9457 (Problem Details for HTTP APIs) に準拠したエラー表現.
// Ref: #/components/schemas/ProblemDetails
type ProblemDetails struct {
	// 問題の種別を示す安定した URI。クライアントは status
	// ではなくこの値で分岐する。 同じ status でも原因が異なれば別の URI
	// を与える（例 404 は経路が無い not-found と、対象が無い resource-not-found
	// に分かれる）。 URI は識別子であり、解決可能である必要はない。.
	Type url.URL `json:"type"`
	// 問題種別の短い人間可読な要約.
	Title string `json:"title"`
	// HTTP ステータスコード.
	Status int `json:"status"`
	// 今回の発生に固有の人間可読な説明.
	Detail OptString `json:"detail"`
	// 問題が発生した具体的なリソースを示す URI.
	Instance OptURI `json:"instance"`
	// 違反したフィールドの一覧（RFC 9457 の拡張メンバー）。
	// フィールドを特定できない場合はこのメンバー自体を省略する（空配列は返さない）。
	// 判明した違反のみを含み、網羅は保証しない。.
	InvalidParams []InvalidParam `json:"invalid-params"`
}

// GetType returns the value of Type.
func (s *ProblemDetails) GetType() url.URL {
	return s.Type
}

// GetTitle returns the value of Title.
func (s *ProblemDetails) GetTitle() string {
	return s.Title
}

// GetStatus returns the value of Status.
func (s *ProblemDetails) GetStatus() int {
	return s.Status
}

// GetDetail returns the value of Detail.
func (s *ProblemDetails) GetDetail() OptString {
	return s.Detail
}

// GetInstance returns the value of Instance.
func (s *ProblemDetails) GetInstance() OptURI {
	return s.Instance
}

// GetInvalidParams returns the value of InvalidParams.
func (s *ProblemDetails) GetInvalidParams() []InvalidParam {
	return s.InvalidParams
}

// SetType sets the value of Type.
func (s *ProblemDetails) SetType(val url.URL) {
	s.Type = val
}

// SetTitle sets the value of Title.
func (s *ProblemDetails) SetTitle(val string) {
	s.Title = val
}

// SetStatus sets the value of Status.
func (s *ProblemDetails) SetStatus(val int) {
	s.Status = val
}

// SetDetail sets the value of Detail.
func (s *ProblemDetails) SetDetail(val OptString) {
	s.Detail = val
}

// SetInstance sets the value of Instance.
func (s *ProblemDetails) SetInstance(val OptURI) {
	s.Instance = val
}

// SetInvalidParams sets the value of InvalidParams.
func (s *ProblemDetails) SetInvalidParams(val []InvalidParam) {
	s.InvalidParams = val
}

// ProblemResponseStatusCode wraps ProblemDetails with StatusCode.
type ProblemResponseStatusCode struct {
	StatusCode int
	Response   ProblemDetails
}

// GetStatusCode returns the value of StatusCode.
func (s *ProblemResponseStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ProblemResponseStatusCode) GetResponse() ProblemDetails {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ProblemResponseStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ProblemResponseStatusCode) SetResponse(val ProblemDetails) {
	s.Response = val
}
