// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// CancelOrder implements cancelOrder operation.
//
// 指定した注文を取り消す。取消できるのは Confirmed 状態の注文のみ。
// 取消に伴う在庫の解放は非同期で行う（注文コンテキストは取消イベントを発行し、
// 在庫コンテキストがそれを購読して解放する）。.
//
// POST /orders/{id}/cancel
func (UnimplementedHandler) CancelOrder(ctx context.Context, params CancelOrderParams) (r *OrderView, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrder implements getOrder operation.
//
// 指定した注文 ID の現在の状態を返す。.
//
// GET /orders/{id}
func (UnimplementedHandler) GetOrder(ctx context.Context, params GetOrderParams) (r *OrderView, _ error) {
	return r, ht.ErrNotImplemented
}

// PlaceOrder implements placeOrder operation.
//
// 注文明細から注文を作成する。作成時に在庫を同期予約し、予約できたときのみ
// 注文を Confirmed
// 状態で確定する。予約が拒否された場合は注文を作成しない。.
//
// POST /orders
func (UnimplementedHandler) PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (r *OrderView, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ProblemResponseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ProblemResponseStatusCode) {
	r = new(ProblemResponseStatusCode)
	return r
}
