// Code generated by ogen, DO NOT EDIT.
package openapi

type CancelOrderRes interface {
	cancelOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type GetShipmentRes interface {
	getShipmentRes()
}

type MarkShippedRes interface {
	markShippedRes()
}

type PlaceOrderRes interface {
	placeOrderRes()
}

type PrepareShipmentRes interface {
	prepareShipmentRes()
}
