// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// CancelOrder implements cancelOrder operation.
	//
	// 指定した注文を取り消す。取消できるのは Confirmed 状態の注文のみ。
	// 取消に伴う在庫の解放は非同期で行う（注文コンテキストは取消イベントを発行し、
	// 在庫コンテキストがそれを購読して解放する）。.
	//
	// POST /orders/{id}/cancel
	CancelOrder(ctx context.Context, params CancelOrderParams) (*OrderView, error)
	// GetOrder implements getOrder operation.
	//
	// 指定した注文 ID の現在の状態を返す。.
	//
	// GET /orders/{id}
	GetOrder(ctx context.Context, params GetOrderParams) (*OrderView, error)
	// PlaceOrder implements placeOrder operation.
	//
	// 注文明細から注文を作成する。作成時に在庫を同期予約し、予約できたときのみ
	// 注文を Confirmed
	// 状態で確定する。予約が拒否された場合は注文を作成しない。.
	//
	// POST /orders
	PlaceOrder(ctx context.Context, req *PlaceOrderRequest) (*OrderView, error)
	// NewError creates *ProblemResponseStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *ProblemResponseStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
