// Code generated by ogen, DO NOT EDIT.
package openapi

type CancelOrderRes interface {
	cancelOrderRes()
}

type GetOrderRes interface {
	getOrderRes()
}

type PlaceOrderRes interface {
	placeOrderRes()
}
