// Code generated by ogen, DO NOT EDIT.

package openapi

import (
	"fmt"

	"github.com/go-faster/errors"
	"github.com/ogen-go/ogen/validate"
)

func (s *CancelOrderBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelOrderConflict) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelOrderNotFound) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *CancelOrderUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetOrderBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetOrderNotFound) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetOrderUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentNotFound) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *GetShipmentUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *InvalidParam) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Code.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "code",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s InvalidParamCode) Validate() error {
	switch s {
	case "required":
		return nil
	case "type":
		return nil
	case "min_length":
		return nil
	case "max_length":
		return nil
	case "pattern":
		return nil
	case "unique_items":
		return nil
	case "invalid_param":
		return nil
	case "body_required":
		return nil
	case "invalid":
		return nil
	case "empty_order":
		return nil
	case "invalid_sku":
		return nil
	case "invalid_quantity":
		return nil
	case "invalid_money_amount":
		return nil
	case "invalid_money_currency":
		return nil
	case "invalid_customer_id":
		return nil
	case "invalid_order_id":
		return nil
	case "invalid_reservation_ref":
		return nil
	case "invalid_shipment_id":
		return nil
	case "invalid_tracking_number":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}

func (s *MarkShippedBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *MarkShippedConflict) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *MarkShippedNotFound) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *MarkShippedRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.TrackingNumber)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "trackingNumber",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *MarkShippedUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *OrderView) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Lines == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "lines",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PlaceOrderBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PlaceOrderConflict) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PlaceOrderRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if s.Lines == nil {
			return errors.New("nil is invalid value")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "lines",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PlaceOrderServiceUnavailable) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PlaceOrderUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PrepareShipmentBadRequest) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PrepareShipmentConflict) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PrepareShipmentNotFound) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *PrepareShipmentRequest) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := (validate.String{
			MinLength:     1,
			MinLengthSet:  true,
			MaxLength:     0,
			MaxLengthSet:  false,
			Email:         false,
			Hostname:      false,
			Regex:         nil,
			MinNumeric:    0,
			MinNumericSet: false,
			MaxNumeric:    0,
			MaxNumericSet: false,
		}).Validate(string(s.OrderId)); err != nil {
			return errors.Wrap(err, "string")
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "orderId",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *PrepareShipmentUnprocessableEntity) Validate() error {
	alias := (*ProblemResponseStatusCode)(s)
	if err := alias.Validate(); err != nil {
		return err
	}
	return nil
}

func (s *ProblemDetails) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		var failures []validate.FieldError
		for i, elem := range s.InvalidParams {
			if err := func() error {
				if err := elem.Validate(); err != nil {
					return err
				}
				return nil
			}(); err != nil {
				failures = append(failures, validate.FieldError{
					Name:  fmt.Sprintf("[%d]", i),
					Error: err,
				})
			}
		}
		if len(failures) > 0 {
			return &validate.Error{Fields: failures}
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "invalid-params",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ProblemResponseStatusCode) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Response.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "Response",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s *ShipmentView) Validate() error {
	if s == nil {
		return validate.ErrNilPointer
	}

	var failures []validate.FieldError
	if err := func() error {
		if err := s.Status.Validate(); err != nil {
			return err
		}
		return nil
	}(); err != nil {
		failures = append(failures, validate.FieldError{
			Name:  "status",
			Error: err,
		})
	}
	if len(failures) > 0 {
		return &validate.Error{Fields: failures}
	}
	return nil
}

func (s ShipmentViewStatus) Validate() error {
	switch s {
	case "preparing":
		return nil
	case "shipped":
		return nil
	default:
		return errors.Errorf("invalid value: %v", s)
	}
}
