// Code generated by ogen, DO NOT EDIT.

package openapi

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation OperationName = "CancelOrder"
	GetOrderOperation    OperationName = "GetOrder"
	PlaceOrderOperation  OperationName = "PlaceOrder"
)
